web:
  build: .
  command: 'bash -c ''npm install; npm start'''
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  volumes:
    - '.:/app/user'
dev-db:
  image: postgres:13
  restart: always
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: hieudang
    POSTGRES_DB: cnpm
  ports:
    - 5432
adminer:
  image: adminer
  restart: always
  ports:
    - 8080:8080